"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { CrmShell } from "@/components/crm-shell";
import { PhotoAnnotator } from "@/components/photo-annotator";
import { useWorkspace } from "@/lib/use-workspace";

type JobDetail = { id:string; title:string; stage:string; contract_value:number; next_action:string|null; next_action_at:string|null; client_id:string; property_id:string|null; workflow_stage_id:string|null; workflow_id:string|null; owner_id:string|null; project_manager_id:string|null;lead_source:string|null;job_type_name:string|null;description:string|null;insurance_carrier:string|null;claim_number:string|null;adjuster_name:string|null;adjuster_phone:string|null;adjuster_email:string|null;inspection_date:string|null;production_start_date:string|null;completion_date:string|null; workflow_stages:{name:string;color:string}|null; clients:{first_name:string;last_name:string;email:string|null;phone:string|null}|null; properties:{address_1:string;city:string;state:string;postal_code:string}|null };
type Activity = { id:string; kind:string; body:string; occurred_at:string };
type FileRow = { id:string; filename:string; storage_path:string; content_type:string|null; size_bytes:number; created_at:string; signedUrl?:string };
type TaskRow = { id:string;title:string;category:string;due_date:string|null;completed_at:string|null };
type WorkflowStage = {id:string;name:string;color:string};
type TeamMember={id:string;full_name:string};

export default function JobPage() {
  const { id } = useParams<{ id:string }>();
  const { supabase, organizationId, loading, userName, user } = useWorkspace();
  const [job,setJob]=useState<JobDetail|null>(null); const [activities,setActivities]=useState<Activity[]>([]); const [files,setFiles]=useState<FileRow[]>([]);
  const [note,setNote]=useState(""); const [busy,setBusy]=useState(false); const [selectedPhoto,setSelectedPhoto]=useState<number|null>(null); const [editingPhoto,setEditingPhoto]=useState<FileRow|null>(null); const [selectedDocument,setSelectedDocument]=useState<FileRow|null>(null); const documentRef=useRef<HTMLInputElement>(null); const photoRef=useRef<HTMLInputElement>(null);
  const [tasks,setTasks]=useState<TaskRow[]>([]),[taskTitle,setTaskTitle]=useState(""),[taskCategory,setTaskCategory]=useState("general"),[taskDue,setTaskDue]=useState(""),[taskSchemaReady,setTaskSchemaReady]=useState(true);
  const [workflowStages,setWorkflowStages]=useState<WorkflowStage[]>([]),[team,setTeam]=useState<TeamMember[]>([]),[editing,setEditing]=useState(false),[edit,setEdit]=useState({title:"",first_name:"",last_name:"",email:"",phone:"",address_1:"",city:"",state:"",postal_code:"",contract_value:"",next_action:"",next_action_at:"",workflow_stage_id:"",owner_id:"",project_manager_id:"",lead_source:"",job_type_name:"Residential",description:"",insurance_carrier:"",claim_number:"",adjuster_name:"",adjuster_phone:"",adjuster_email:"",inspection_date:"",production_start_date:"",completion_date:""});
  const [emailing,setEmailing]=useState(false),[emailError,setEmailError]=useState(""),[emailDraft,setEmailDraft]=useState({to:"",subject:"",body:""});

  useEffect(()=>{ if(!organizationId)return; (async()=>{
    const {data}=await supabase.from("jobs").select("id,title,stage,contract_value,next_action,next_action_at,client_id,property_id,workflow_id,workflow_stage_id,owner_id,project_manager_id,lead_source,job_type_name,description,insurance_carrier,claim_number,adjuster_name,adjuster_phone,adjuster_email,inspection_date,production_start_date,completion_date,workflow_stages(name,color),clients(first_name,last_name,email,phone),properties(address_1,city,state,postal_code)").eq("id",id).single(); const loaded=data as unknown as JobDetail;setJob(loaded);
    const {data:members}=await supabase.from("organization_members").select("user_id,profiles(full_name)").eq("organization_id",organizationId);
    setTeam(((members||[]) as unknown as Array<{user_id:string;profiles:{full_name:string}|null}>).map(member=>({id:member.user_id,full_name:member.profiles?.full_name||"Team member"})));
    if(loaded?.workflow_id){const {data:s}=await supabase.from("workflow_stages").select("id,name,color").eq("workflow_id",loaded.workflow_id).order("position");setWorkflowStages((s||[]) as WorkflowStage[])}
    const [{data:a},{data:f},{data:t,error:taskError}]=await Promise.all([supabase.from("activities").select("id,kind,body,occurred_at").eq("job_id",id).order("occurred_at",{ascending:false}),supabase.from("files").select("id,filename,storage_path,content_type,size_bytes,created_at").eq("job_id",id).order("created_at",{ascending:false}),supabase.from("job_tasks").select("id,title,category,due_date,completed_at").eq("job_id",id).order("completed_at").order("sort_order")]);
    setActivities((a||[]) as Activity[]);
    if(taskError)setTaskSchemaReady(false);else setTasks((t||[]) as TaskRow[]);
    const rows=(f||[]) as FileRow[]; const signed=await Promise.all(rows.map(async file=>{const {data:url}=await supabase.storage.from("job-files").createSignedUrl(file.storage_path,3600);return {...file,signedUrl:url?.signedUrl};})); setFiles(signed);
  })(); },[id,organizationId,supabase]);

  async function logActivity(kind:string,body:string){if(!job||!user)return;const {data}=await supabase.from("activities").insert({organization_id:organizationId,job_id:job.id,actor_id:user.id,kind,body}).select("id,kind,body,occurred_at").single();if(data)setActivities(current=>[data as Activity,...current])}
  async function addNote(){if(!note.trim()||!job||!user)return;setBusy(true);await logActivity("note",note.trim());setNote("");setBusy(false)}
  function beginEmail(){if(!job)return;setEmailError("");setEmailDraft({to:job.clients?.email||"",subject:`Your ${job.title}`,body:`Hi ${job.clients?.first_name||"there"},\n\n`});setEmailing(true)}
  async function sendEmail(){if(!job||!emailDraft.to.trim()||!emailDraft.subject.trim()||!emailDraft.body.trim())return;setBusy(true);setEmailError("");try{const response=await fetch("/api/gmail/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:job.id,...emailDraft})});const result=await response.json();if(!response.ok)throw new Error(result.error||"The email could not be sent.");if(result.activity)setActivities(current=>[result.activity as Activity,...current]);setEmailing(false)}catch(error){setEmailError(error instanceof Error?error.message:"The email could not be sent.")}finally{setBusy(false)}}
  function beginEdit(){if(!job)return;setEdit({title:job.title,first_name:job.clients?.first_name||"",last_name:job.clients?.last_name||"",email:job.clients?.email||"",phone:job.clients?.phone||"",address_1:job.properties?.address_1||"",city:job.properties?.city||"",state:job.properties?.state||"",postal_code:job.properties?.postal_code||"",contract_value:String(job.contract_value||0),next_action:job.next_action||"",next_action_at:job.next_action_at?.slice(0,10)||"",workflow_stage_id:job.workflow_stage_id||"",owner_id:job.owner_id||"",project_manager_id:job.project_manager_id||"",lead_source:job.lead_source||"",job_type_name:job.job_type_name||"Residential",description:job.description||"",insurance_carrier:job.insurance_carrier||"",claim_number:job.claim_number||"",adjuster_name:job.adjuster_name||"",adjuster_phone:job.adjuster_phone||"",adjuster_email:job.adjuster_email||"",inspection_date:job.inspection_date||"",production_start_date:job.production_start_date||"",completion_date:job.completion_date||""});setEditing(true)}
  async function saveDetails(){if(!job)return;setBusy(true);const stage=workflowStages.find(s=>s.id===edit.workflow_stage_id);const jobPatch={title:edit.title,contract_value:Number(edit.contract_value)||0,next_action:edit.next_action||null,next_action_at:edit.next_action_at?`${edit.next_action_at}T12:00:00`:null,workflow_stage_id:edit.workflow_stage_id||null,owner_id:edit.owner_id||null,project_manager_id:edit.project_manager_id||null,lead_source:edit.lead_source||null,job_type_name:edit.job_type_name||null,description:edit.description||null,insurance_carrier:edit.insurance_carrier||null,claim_number:edit.claim_number||null,adjuster_name:edit.adjuster_name||null,adjuster_phone:edit.adjuster_phone||null,adjuster_email:edit.adjuster_email||null,inspection_date:edit.inspection_date||null,production_start_date:edit.production_start_date||null,completion_date:edit.completion_date||null,updated_at:new Date().toISOString()};await Promise.all([supabase.from("jobs").update(jobPatch).eq("id",job.id),supabase.from("clients").update({first_name:edit.first_name,last_name:edit.last_name,email:edit.email||null,phone:edit.phone||null}).eq("id",job.client_id),job.property_id?supabase.from("properties").update({address_1:edit.address_1,city:edit.city,state:edit.state,postal_code:edit.postal_code}).eq("id",job.property_id):Promise.resolve()]);const changed:string[]=[];if(job.workflow_stage_id!==edit.workflow_stage_id)changed.push(`status moved to ${stage?.name||"Unassigned"}`);if(job.next_action!==(edit.next_action||null))changed.push(`next action set to “${edit.next_action||"None"}”`);if(job.owner_id!==(edit.owner_id||null))changed.push("salesperson updated");if(job.project_manager_id!==(edit.project_manager_id||null))changed.push("project manager updated");if(!changed.length)changed.push("job details updated");setJob({...job,...jobPatch,next_action_at:jobPatch.next_action_at,workflow_stages:stage?{name:stage.name,color:stage.color}:job.workflow_stages,clients:{first_name:edit.first_name,last_name:edit.last_name,email:edit.email||null,phone:edit.phone||null},properties:job.properties?{address_1:edit.address_1,city:edit.city,state:edit.state,postal_code:edit.postal_code}:null});await logActivity("job update",changed.join(" · "));setEditing(false);setBusy(false)}
  async function addTask(){if(!taskTitle.trim()||!job||!user)return;setBusy(true);const title=taskTitle.trim();const {data,error}=await supabase.from("job_tasks").insert({organization_id:organizationId,job_id:job.id,title,category:taskCategory,due_date:taskDue||null,created_by:user.id,sort_order:tasks.length}).select("id,title,category,due_date,completed_at").single();if(error)setTaskSchemaReady(false);if(data){setTasks(current=>[...current,data as TaskRow]);await logActivity("task created",`${title}${taskDue?` · due ${new Date(`${taskDue}T12:00:00`).toLocaleDateString()}`:""}`)}setTaskTitle("");setTaskDue("");setBusy(false)}
  async function toggleTask(task:TaskRow){const completed_at=task.completed_at?null:new Date().toISOString();setTasks(current=>current.map(item=>item.id===task.id?{...item,completed_at}:item));await supabase.from("job_tasks").update({completed_at}).eq("id",task.id);await logActivity(completed_at?"task completed":"task reopened",task.title)}
  async function deleteTask(task:TaskRow){setTasks(current=>current.filter(item=>item.id!==task.id));await supabase.from("job_tasks").delete().eq("id",task.id)}
  async function upload(e:ChangeEvent<HTMLInputElement>){const selected=Array.from(e.target.files||[]);if(!selected.length||!job||!user)return;setBusy(true);const uploaded:string[]=[];for(const file of selected){const path=`${organizationId}/${job.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from("job-files").upload(path,file);if(!error){const {data}=await supabase.from("files").insert({organization_id:organizationId,client_id:job.client_id,job_id:job.id,storage_path:path,filename:file.name,content_type:file.type,size_bytes:file.size,uploaded_by:user.id}).select("id,filename,storage_path,content_type,size_bytes,created_at").single();if(data){const {data:url}=await supabase.storage.from("job-files").createSignedUrl(path,3600);setFiles(c=>[{...(data as FileRow),signedUrl:url?.signedUrl},...c]);uploaded.push(file.name)}}}if(uploaded.length)await logActivity("files uploaded",uploaded.join(", "));setBusy(false);e.target.value=""}
  function openFile(file:FileRow){if(file.signedUrl)window.open(file.signedUrl,"_blank","noopener,noreferrer")}
  function viewDocument(file:FileRow){if(file.content_type==="application/pdf"||file.filename.toLowerCase().endsWith(".pdf"))setSelectedDocument(file);else openFile(file)}
  async function downloadFile(file:FileRow){if(!file.signedUrl)return;const response=await fetch(file.signedUrl);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=file.filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
  async function saveAnnotation(blob:Blob,filename:string){if(!job||!user)return;const file=new File([blob],filename,{type:"image/png"});const path=`${organizationId}/${job.id}/${Date.now()}-${filename.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from("job-files").upload(path,file);if(error)return;const {data}=await supabase.from("files").insert({organization_id:organizationId,client_id:job.client_id,job_id:job.id,storage_path:path,filename,content_type:"image/png",size_bytes:file.size,uploaded_by:user.id}).select("id,filename,storage_path,content_type,size_bytes,created_at").single();if(data){const {data:url}=await supabase.storage.from("job-files").createSignedUrl(path,3600);setFiles(c=>[{...(data as FileRow),signedUrl:url?.signedUrl},...c]);setEditingPhoto(null);setSelectedPhoto(null)}}

  const photos=files.filter(f=>f.content_type?.startsWith("image/")); const documents=files.filter(f=>!f.content_type?.startsWith("image/"));
  useEffect(()=>{if(selectedPhoto===null&&!selectedDocument&&!editingPhoto)return;const move=(direction:number)=>setSelectedPhoto(current=>current===null?null:(current+direction+photos.length)%photos.length);const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setSelectedPhoto(null);setSelectedDocument(null);setEditingPhoto(null)}if(selectedPhoto!==null&&event.key==="ArrowRight")move(1);if(selectedPhoto!==null&&event.key==="ArrowLeft")move(-1)};document.addEventListener("keydown",key);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=""}},[editingPhoto,photos.length,selectedDocument,selectedPhoto]);

  if(loading||!job)return <main className="auth-loading"><span>R</span></main>;
  return <CrmShell userName={userName}><div className="content job-detail"><div className="job-detail-head"><div><p className="eyebrow">JOB WORKSPACE</p><h1>{job.title}</h1><p>{job.clients?.first_name} {job.clients?.last_name} · {job.properties?.address_1}, {job.properties?.city}</p></div><div className="job-head-actions"><span className="stage workflow-status" style={job.workflow_stages?.color?{background:`${job.workflow_stages.color}22`,color:job.workflow_stages.color,borderColor:`${job.workflow_stages.color}55`}:undefined}>{job.workflow_stages?.name||job.stage.replaceAll("_"," ")}</span><button className="job-email-button" onClick={beginEmail}>✉ Email client</button><Link className="job-measurements-link" href={`/jobs/${job.id}/measurements`}>⌗ Measurements</Link><button onClick={beginEdit}>✎ Edit job</button></div></div><div className="detail-grid">
    <section className="panel"><div className="panel-head"><div><h3>Job overview</h3><p>The operational source of truth</p></div><button className="overview-edit" onClick={beginEdit}>✎ Edit details</button></div><div className="overview-grid"><div><small>Client</small><b>{job.clients?.first_name} {job.clients?.last_name}</b><p>{job.clients?.email}<br/>{job.clients?.phone}</p></div><div><small>Property</small><b>{job.properties?.address_1||"No property"}</b><p>{job.properties?.city}, {job.properties?.state} {job.properties?.postal_code}</p></div><div><small>Contract value</small><b>${Number(job.contract_value).toLocaleString()}</b><p>From approved estimate</p></div><div className="next-action-card"><small>Next action</small><b>{job.next_action||"Not set"}</b><p>{job.next_action_at?`Due ${new Date(job.next_action_at).toLocaleDateString()}`:"Add a due date to keep it moving"}</p></div></div><div className="job-field-strip"><div><small>Salesperson</small><b>{team.find(member=>member.id===job.owner_id)?.full_name||"Unassigned"}</b></div><div><small>Project manager</small><b>{team.find(member=>member.id===job.project_manager_id)?.full_name||"Unassigned"}</b></div><div><small>Lead source</small><b>{job.lead_source||"Not set"}</b></div><div><small>Job type</small><b>{job.job_type_name||"Residential"}</b></div><div><small>Inspection</small><b>{job.inspection_date?new Date(`${job.inspection_date}T12:00:00`).toLocaleDateString():"Not scheduled"}</b></div><div><small>Production</small><b>{job.production_start_date?new Date(`${job.production_start_date}T12:00:00`).toLocaleDateString():"Not scheduled"}</b></div></div>{job.description&&<div className="job-description"><small>Job description</small><p>{job.description}</p></div>}{(job.insurance_carrier||job.claim_number||job.adjuster_name)&&<div className="insurance-summary"><span>◆</span><div><small>Insurance claim</small><b>{job.insurance_carrier||"Carrier not set"}{job.claim_number?` · Claim ${job.claim_number}`:""}</b><p>{job.adjuster_name||"No adjuster"}{job.adjuster_phone?` · ${job.adjuster_phone}`:""}{job.adjuster_email?` · ${job.adjuster_email}`:""}</p></div></div>}</section>
    <section className="panel"><div className="panel-head"><div><h3>Notes & timeline</h3><p>Every important job event</p></div></div><div className="note-compose"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a job note..."/><button disabled={busy||!note.trim()} onClick={addNote}>Add note</button></div><div className="timeline">{activities.map(a=><article key={a.id}><span>✎</span><div><b>{a.kind}</b><p>{a.body}</p><small>{new Date(a.occurred_at).toLocaleString()}</small></div></article>)}{!activities.length&&<div className="empty">No activity yet.</div>}</div></section>
    <section className="panel tasks-panel"><div className="panel-head"><div><h3>Tasks & checklist</h3><p>{tasks.filter(task=>task.completed_at).length} of {tasks.length} completed</p></div></div>{!taskSchemaReady?<div className="task-migration"><b>Activate job tasks</b><p>Run the newest Job Tasks migration in Supabase once, then refresh this page.</p></div>:<><div className="task-compose"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addTask()} placeholder="What needs to happen next?"/><select value={taskCategory} onChange={e=>setTaskCategory(e.target.value)}><option value="general">General</option><option value="sales">Sales</option><option value="preproduction">Pre-Production</option><option value="production">Production</option><option value="closeout">Closeout</option></select><input type="date" value={taskDue} onChange={e=>setTaskDue(e.target.value)}/><button disabled={busy||!taskTitle.trim()} onClick={addTask}>＋ Add task</button></div><div className="task-list">{tasks.map(task=><article className={task.completed_at?"complete":""} key={task.id}><button className="task-check" onClick={()=>toggleTask(task)}>{task.completed_at?"✓":""}</button><div><b>{task.title}</b><p><span>{task.category.replaceAll("production","production").replaceAll("preproduction","pre-production")}</span>{task.due_date&&<> · Due {new Date(`${task.due_date}T12:00:00`).toLocaleDateString()}</>}</p></div><button className="task-delete" onClick={()=>deleteTask(task)}>×</button></article>)}{!tasks.length&&<div className="empty">No tasks yet. Add the first next step.</div>}</div></>}</section>
    <section className="panel photos-panel"><div className="panel-head"><div><h3>Photo gallery</h3><p>Roof, damage, measurements, progress, and completion</p></div><button onClick={()=>photoRef.current?.click()}>＋ Add photos</button><input ref={photoRef} hidden type="file" accept="image/*" multiple onChange={upload}/></div>{photos.length?<div className="photo-grid">{photos.map((photo,index)=><button key={photo.id} onClick={()=>setSelectedPhoto(index)} title={photo.filename}><img src={photo.signedUrl} alt={photo.filename}/><span>{photo.filename}</span></button>)}</div>:<div className="empty">No photos yet. Add the first job photo.</div>}</section>
    <section className="panel files-panel"><div className="panel-head"><div><h3>Documents</h3><p>Contracts, estimates, permits, invoices, and other files</p></div><button onClick={()=>documentRef.current?.click()}>＋ Upload document</button><input ref={documentRef} hidden type="file" multiple onChange={upload}/></div>{documents.map(file=><div className="file-row" key={file.id}><span>▤</span><button className="file-name" onClick={()=>viewDocument(file)}><b>{file.filename}</b><p>{Math.max(1,Math.round(file.size_bytes/1024))} KB · {new Date(file.created_at).toLocaleDateString()}</p></button><div className="file-actions"><button onClick={()=>viewDocument(file)}>View</button><button onClick={()=>downloadFile(file)}>↓ Download</button></div></div>)}{!documents.length&&<div className="empty">No documents yet.</div>}</section>
  </div></div>
  {editing&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(false)}><section className="modal job-edit-modal expanded"><button className="modal-close" onClick={()=>setEditing(false)}>×</button><p className="eyebrow">JOB DETAILS</p><h2>Edit job workspace</h2><p>Update the customer, team, dates, insurance details, and next action in one place.</p><div className="form-grid">
    <div className="form-section-title wide"><b>Job & customer</b></div>
    <label className="wide">Job title<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>First name<input value={edit.first_name} onChange={e=>setEdit({...edit,first_name:e.target.value})}/></label><label>Last name<input value={edit.last_name} onChange={e=>setEdit({...edit,last_name:e.target.value})}/></label><label>Email<input value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><label>Phone<input value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label><label className="wide">Property address<input value={edit.address_1} onChange={e=>setEdit({...edit,address_1:e.target.value})}/></label><label>City<input value={edit.city} onChange={e=>setEdit({...edit,city:e.target.value})}/></label><label>State<input value={edit.state} onChange={e=>setEdit({...edit,state:e.target.value})}/></label><label>ZIP code<input value={edit.postal_code} onChange={e=>setEdit({...edit,postal_code:e.target.value})}/></label>
    <div className="form-section-title wide"><b>Operations</b></div>
    <label>Workflow status<select value={edit.workflow_stage_id} onChange={e=>setEdit({...edit,workflow_stage_id:e.target.value})}>{workflowStages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></label><label>Salesperson<select value={edit.owner_id} onChange={e=>setEdit({...edit,owner_id:e.target.value})}><option value="">Unassigned</option>{team.map(member=><option key={member.id} value={member.id}>{member.full_name}</option>)}</select></label><label>Project manager<select value={edit.project_manager_id} onChange={e=>setEdit({...edit,project_manager_id:e.target.value})}><option value="">Unassigned</option>{team.map(member=><option key={member.id} value={member.id}>{member.full_name}</option>)}</select></label><label>Lead source<input value={edit.lead_source} placeholder="Referral, Google, Facebook…" onChange={e=>setEdit({...edit,lead_source:e.target.value})}/></label><label>Job type<select value={edit.job_type_name} onChange={e=>setEdit({...edit,job_type_name:e.target.value})}><option>Residential</option><option>Commercial</option><option>Insurance</option><option>Retail</option><option>Repair</option></select></label><label>Contract value<input type="number" value={edit.contract_value} onChange={e=>setEdit({...edit,contract_value:e.target.value})}/></label><label>Inspection date<input type="date" value={edit.inspection_date} onChange={e=>setEdit({...edit,inspection_date:e.target.value})}/></label><label>Production start<input type="date" value={edit.production_start_date} onChange={e=>setEdit({...edit,production_start_date:e.target.value})}/></label><label>Completion date<input type="date" value={edit.completion_date} onChange={e=>setEdit({...edit,completion_date:e.target.value})}/></label><label className="wide">Next action<input value={edit.next_action} onChange={e=>setEdit({...edit,next_action:e.target.value})}/></label><label>Next action due<input type="date" value={edit.next_action_at} onChange={e=>setEdit({...edit,next_action_at:e.target.value})}/></label><label className="wide">Job description<textarea value={edit.description} placeholder="Project scope, homeowner goals, or important context…" onChange={e=>setEdit({...edit,description:e.target.value})}/></label>
    <div className="form-section-title wide"><b>Insurance information</b><span>Optional</span></div>
    <label>Insurance carrier<input value={edit.insurance_carrier} onChange={e=>setEdit({...edit,insurance_carrier:e.target.value})}/></label><label>Claim number<input value={edit.claim_number} onChange={e=>setEdit({...edit,claim_number:e.target.value})}/></label><label>Adjuster name<input value={edit.adjuster_name} onChange={e=>setEdit({...edit,adjuster_name:e.target.value})}/></label><label>Adjuster phone<input value={edit.adjuster_phone} onChange={e=>setEdit({...edit,adjuster_phone:e.target.value})}/></label><label className="wide">Adjuster email<input value={edit.adjuster_email} onChange={e=>setEdit({...edit,adjuster_email:e.target.value})}/></label>
  </div><div className="modal-actions"><button onClick={()=>setEditing(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={saveDetails}>{busy?"Saving…":"Save changes"}</button></div></section></div>}
  {emailing&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEmailing(false)}><section className="modal email-compose-modal"><button className="modal-close" onClick={()=>setEmailing(false)}>×</button><p className="eyebrow">GMAIL</p><h2>Email {job.clients?.first_name||"client"}</h2><p>This sends from your connected Roofnut Gmail and records a copy in this job.</p><div className="email-compose-fields"><label>To<input type="email" value={emailDraft.to} onChange={e=>setEmailDraft({...emailDraft,to:e.target.value})}/></label><label>Subject<input value={emailDraft.subject} onChange={e=>setEmailDraft({...emailDraft,subject:e.target.value})}/></label><label>Message<textarea autoFocus value={emailDraft.body} onChange={e=>setEmailDraft({...emailDraft,body:e.target.value})}/></label></div>{emailError&&<div className="email-error">{emailError}</div>}<div className="modal-actions"><button onClick={()=>setEmailing(false)}>Save for later</button><button className="primary-button" disabled={busy||!emailDraft.to.trim()||!emailDraft.subject.trim()||!emailDraft.body.trim()} onClick={sendEmail}>{busy?"Sending…":"Send with Gmail →"}</button></div></section></div>}
  {selectedPhoto!==null&&photos[selectedPhoto]&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Job photo viewer" onMouseDown={e=>e.target===e.currentTarget&&setSelectedPhoto(null)}><div className="lightbox-bar"><div><b>{photos[selectedPhoto].filename}</b><span>{selectedPhoto+1} of {photos.length}</span></div><div className="viewer-actions"><button className="download-button" onClick={()=>setEditingPhoto(photos[selectedPhoto])}>✎ Edit</button><button className="download-button" onClick={()=>downloadFile(photos[selectedPhoto])}>↓ Download</button><button onClick={()=>setSelectedPhoto(null)} aria-label="Close photo viewer">×</button></div></div>{photos.length>1&&<button className="lightbox-arrow previous" onClick={()=>setSelectedPhoto((selectedPhoto-1+photos.length)%photos.length)} aria-label="Previous photo">‹</button>}<img src={photos[selectedPhoto].signedUrl} alt={photos[selectedPhoto].filename}/>{photos.length>1&&<button className="lightbox-arrow next" onClick={()=>setSelectedPhoto((selectedPhoto+1)%photos.length)} aria-label="Next photo">›</button>}<div className="lightbox-help">Use ← → arrow keys to browse · Esc to close</div></div>}
  {selectedDocument&&<div className="document-viewer" role="dialog" aria-modal="true" aria-label="PDF viewer"><div className="lightbox-bar"><div><b>{selectedDocument.filename}</b><span>Secure PDF preview</span></div><div className="viewer-actions"><button className="download-button" onClick={()=>downloadFile(selectedDocument)}>↓ Download</button><button onClick={()=>setSelectedDocument(null)} aria-label="Close PDF viewer">×</button></div></div><iframe src={selectedDocument.signedUrl} title={selectedDocument.filename}/></div>}
  {editingPhoto?.signedUrl&&<PhotoAnnotator src={editingPhoto.signedUrl} filename={editingPhoto.filename} onClose={()=>setEditingPhoto(null)} onSave={saveAnnotation}/>}</CrmShell>;
}
